import pybullet as p
import pybullet_data
import numpy as np
import os
import time
import config
from robot import Panda


## functions that the language model (LM) can use
# move to position and orientation
def move_to_pose(ee_position, ee_euler):
    ee_euler[0] += np.pi
    for i in range (1000):
        panda.move_to_pose(ee_position=ee_position, ee_quaternion=p.getQuaternionFromEuler(ee_euler), positionGain=0.01)
        p.stepSimulation()
        time.sleep(config.control_dt)
# open gripper
def open_gripper():
    for i in range(300):
        panda.open_gripper()
        p.stepSimulation()
        time.sleep(config.control_dt)
# open gripper
def close_gripper():
    for i in range(300):
        panda.close_gripper()
        p.stepSimulation()
        time.sleep(config.control_dt)
# terminate
def task_completed():
    p.disconnect()


# create simulation and place camera
physicsClient = p.connect(p.GUI)
p.setGravity(0, 0, -9.81)
p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)
p.resetDebugVisualizerCamera(cameraDistance=config.cameraDistance, 
                                cameraYaw=config.cameraYaw,
                                cameraPitch=config.cameraPitch, 
                                cameraTargetPosition=config.cameraTargetPosition)

# load the objects
urdfRootPath = pybullet_data.getDataPath()
plane = p.loadURDF(os.path.join(urdfRootPath, "plane.urdf"), basePosition=[0, 0, -0.625])
table = p.loadURDF(os.path.join(urdfRootPath, "table/table.urdf"), basePosition=[0.5, 0, -0.625])
cube = p.loadURDF("objects/simple_objects/cube.urdf", basePosition=[0.6, 0, 0.2], baseOrientation=p.getQuaternionFromEuler([0, np.pi/2, 0]))

# load the robot
panda = Panda(basePosition=config.baseStartPosition,
                baseOrientation=p.getQuaternionFromEuler(config.baseStartOrientationE),
                jointStartPositions=config.jointStartPositions)

# let the scene initialize
for i in range(100):
    p.stepSimulation()
    time.sleep(config.control_dt)

# response
'''
The center of the beam is in position [0.6, 0, 0.2]
The beam is 0.05 wide, 0.05 depth, and 0.4 height
'''

# enter the code generated by the LM below:


# Step 1: Move to pre-grasp pose (above and in front of beam)
move_to_pose([0.7, 0.0, 0.3], [0.0, -np.pi/2, 0.0])

# Step 2: Move to grasp pose (insert fingers beside beam)
move_to_pose([0.63, 0.0, 0.2], [0.0, -0.1, 0.0])

# Step 3: Close gripper to grasp the beam
close_gripper()

# Step 4: Lift the beam vertically to clear the table
move_to_pose([0.63, 0.0, 0.4], [0.0, -1., 0.0])

# Task completed
task_completed()