import pybullet as p
import pybullet_data
import numpy as np
import os
import time
import config
from robot import Panda


## internal function
# move to position and orientation
def move_to_pose(ee_position, ee_euler):
    for i in range (1000):
        panda.move_to_pose(ee_position=ee_position, ee_quaternion=p.getQuaternionFromEuler(ee_euler), positionGain=0.01)
        p.stepSimulation()
        time.sleep(config.control_dt)

## functions that the LM can use
# side grasp with the fingers along the +-z axis
# at angle = 0 the gripper in pointing along the positive x axis
def side_grasp_vertical(angle):
    ee_euler = [np.pi/2, 0, np.pi/2 + angle]
    state = panda.get_state()
    move_to_pose(state["ee-position"], ee_euler)
# side grasp with the fingers perpendicular to the z axis
# at angle = 0 the gripper in pointing along the positive x axis
def side_grasp_horizontal(angle):
    ee_euler = [np.pi, -np.pi/2, angle]
    state = panda.get_state()
    move_to_pose(state["ee-position"], ee_euler)
# top grasp
# at angle = 0 the fingers are along the +-y axis
def top_grasp(angle):
    ee_euler = [np.pi, 0, angle]
    state = panda.get_state()
    move_to_pose(state["ee-position"], ee_euler)
# move to a given position
def move_to_position(position):
    state = panda.get_state()
    move_to_pose(position, state["ee-euler"])
# open gripper
def open_gripper():
    for i in range(300):
        panda.open_gripper()
        p.stepSimulation()
        time.sleep(config.control_dt)
# close gripper
def close_gripper():
    for i in range(300):
        panda.close_gripper()
        p.stepSimulation()
        time.sleep(config.control_dt)
# terminate
def task_completed():
    p.disconnect()


# create simulation and place camera
physicsClient = p.connect(p.GUI)
p.setGravity(0, 0, -9.81)
p.configureDebugVisualizer(p.COV_ENABLE_GUI, 0)
p.resetDebugVisualizerCamera(cameraDistance=config.cameraDistance, 
                                cameraYaw=config.cameraYaw,
                                cameraPitch=config.cameraPitch, 
                                cameraTargetPosition=config.cameraTargetPosition)

# load the objects
urdfRootPath = pybullet_data.getDataPath()
plane = p.loadURDF(os.path.join(urdfRootPath, "plane.urdf"), basePosition=[0, 0, -0.625])
table = p.loadURDF(os.path.join(urdfRootPath, "table/table.urdf"), basePosition=[0.5, 0, -0.625])
cube = p.loadURDF("objects/simple_objects/cube.urdf", basePosition=[0.6, 0, 0.2], baseOrientation=p.getQuaternionFromEuler([0, np.pi/2, 0]))

# load the robot
panda = Panda(basePosition=config.baseStartPosition,
                baseOrientation=p.getQuaternionFromEuler(config.baseStartOrientationE),
                jointStartPositions=config.jointStartPositions)

# let the scene initialize
for i in range(100):
    p.stepSimulation()
    time.sleep(config.control_dt)

# response
'''
The center of the beam is in position [0.6, 0, 0.2], rotated by 0.7 around z-axis
The beam is 0.05 wide, 0.05 depth, and 0.4 height


the banana is at position [0.4, -0.2, 0.05]. The long side of the banana is rotated around the z-axis by 0.7 radians.
the drawer is facing the robot. it is a large box.
the drawer handle is a horizontal bar attached to the face of the drawer. The center of the handle is position [0.6, 0.2, 0.4]. The width of the handle is 0.1, the height is 0.03, and the depth is 0.05.

'''

# enter the code generated by the LM below:



# Prepare for grasp
open_gripper()
side_grasp_vertical(0.0)

# Move to pre-grasp position (aligned with handle center, but retracted)
move_to_position([0.45, 0.2, 0.4])

# Approach and grasp the handle center
move_to_position([0.6, 0.2, 0.4])
close_gripper()

# Pull the drawer open (move toward the robot base along the x-axis)
move_to_position([0.4, 0.2, 0.4])

# Release and retract
open_gripper()
move_to_position([0.3, 0.2, 0.4])

task_completed()